### ISSUE TITLE
Design improvement

### ISSUE THREAD

**Issue by suchoproduction** [kongulov/nova-tab-translatable#19]
![Snímka obrazovky 2022-06-15 o 20 30 47](https://user-images.githubusercontent.com/6931349/173899741-a7f0d9c3-207f-4810-b6f8-115c52e0f966.png)
![Snímka obrazovky 2022-06-15 o 20 30 05](https://user-images.githubusercontent.com/6931349/173899733-4e597862-98e3-4848-ba28-993b1e9d3cea.png)
![Snímka obrazovky 2022-06-15 o 20 31 34](https://user-images.githubusercontent.com/6931349/173899744-a57f77ae-56f6-4cf5-9ec8-6c2f713d2229.png)
![Snímka obrazovky 2022-06-15 o 20 31 53](https://user-images.githubusercontent.com/6931349/173899746-19d3b0ff-80b8-4338-a789-b4e87480a2fd.png)
![Snímka obrazovky 2022-06-15 o 20 29 28](https://user-images.githubusercontent.com/6931349/173899786-588e51ef-c781-4392-8410-d325b10fd91b.png)
![Snímka obrazovky 2022-06-15 o 20 29 43](https://user-images.githubusercontent.com/6931349/173899797-29e67cb7-562f-41be-a3ea-22ea40f7848f.png)

```css
#nova-tab-translatable {
    border-bottom: 1px solid #eef1f4;

    .tab-items {
        padding: 1rem 1.5rem 0;
        background-color: #eef1f4;
        border-top-left-radius: .5rem;
        border-top-right-radius: .5rem;

        .tab-item {
            font-weight: bold;
            text-transform: none !important;
            color: #7c858e !important;

            &.active {
                color: #4099de !important;
            }

            .text-danger {
                color: #ef4444 !important;
            }
        }
    }
}

[data-testid="preview-resource-modal"],
[dusk$="-detail-component"] {
    #nova-tab-translatable {
        margin-top: -8px;
        border-bottom: none;

        .tab-items {
            margin: 0 -24px -1px !important;
        }
    }
}

[data-testid="preview-resource-modal"] {
    #nova-tab-translatable {
        margin-top: -12px;

        .tab-items {
            margin: 0 -32px -1px !important;
            border-radius: 0;
        }
    }
}

.tab-group {
    .tab-card {
        .tab {
            #nova-tab-translatable {
                .tab-items {
                    margin-top: -1rem !important;
                    border-radius: 0;

                    .tab-item {
                        flex: inherit;
                    }
                }
            }
        }
    }
}

html.dark {
    #nova-tab-translatable {
        border-color: #344155;

        .tab-items {
            background-color: #344155;

            .tab-item {
                color: #8997ac !important;

                &.active {
                    color: #4099de !important;
                }
            }
        }
    }
}

```
